version: '3.8'

services:
  mesa_de_partes:
    build:
      context: .
      dockerfile: Dockerfile
    # Asumimos que tu aplicaci√≥n ahora escucha en el puerto 8000 dentro del contenedor
    ports:
      - "5001:8000" 
    restart: unless-stopped
    
    # üö® CAMBIO AQU√ç: Usamos un Montaje de Enlace
    volumes:
      # La ruta relativa './sqlite_data' apunta a una carpeta en tu m√°quina host.
      - ./sqlite_data:/app/data/ 
      
    # Si quieres tambi√©n montar el c√≥digo fuente para desarrollo:
    # - .:/app